#!/bin/bash
set -eo pipefail

PROJECT_DIR="/gpfs/hpc/home/chenchao/hanc/project/C4_CNB2025"
OUT_DIR="${PROJECT_DIR}/topmed_analysis/filter"

# Input VCF generated by Osprey
INPUT_VCF="${OUT_DIR}/fetal_chb_imputed.cnv.vcf.gz"

# Path to the reference panel R script and files

RSCRIPT="${PROJECT_DIR}/code/refine_C4_haplotypes.R"
BASENAME=$(basename "${INPUT_VCF}" .cnv.vcf.gz)
PCNL_FILE="${OUT_DIR}/${BASENAME}.cnvs.pcnls.txt"
RAW_HAP_FILE="${OUT_DIR}/${BASENAME}_hap_refinement.txt"
FINAL_HAP_FILE="${OUT_DIR}/${BASENAME}_haps_refined.txt"

# Sanity Checks

if [[ ! -f "${RSCRIPT}" ]]; then
    echo "Error: R script not found at ${RSCRIPT}"
    exit 1
fi

if [[ -f "${FINAL_HAP_FILE}" ]]; then
    echo "Warning: Output file ${FINAL_HAP_FILE} already exists. Exiting."
    exit 0
fi

echo "Starting C4 haplotype refinement for: ${BASENAME}..."

# Step 1: Extract variant data using bcftools

echo "Step 1: Extracting PCNL data..."
(
    bcftools query -f 'ID[\t%SAMPLE]\n' "${INPUT_VCF}" | head -n 1
    bcftools query -f 'PST[\t%PST]\n' "${INPUT_VCF}" | head -n 1
    bcftools query -f '%ID[\t%PCN;%PCNL]\n' "${INPUT_VCF}"
) > "${PCNL_FILE}"


# Step 2: Run haplotype refinement R script

echo "Step 2: Running R script refinement..."
Rscript "${RSCRIPT}" "${PCNL_FILE}" ALL > "${RAW_HAP_FILE}"


# Step 3: Format output to merge allele rows per sample

echo "Step 3: Formatting final haplotype table..."
awk -v FS="\t" -v OFS="\t" '{
    if (NR == 1) { 
        print "SAMPLE", "H1", "H2", "Q1", "Q2"
        next 
    }
    if ($2 == 1) { 
        h1 = $4; q1 = $6 
    } else { 
        h2 = $4; q2 = $6 
        print $1, h1, h2, q1, q2 
    }
}' "${RAW_HAP_FILE}" > "${FINAL_HAP_FILE}"

echo "Success! Final refined haplotypes saved to: ${FINAL_HAP_FILE}"

# rm -f "${PCNL_FILE}" "${RAW_HAP_FILE}"

# We filtered out samples with R² > 5 for both H1 and H2 haplotypes after refinement.
# fetal_onlychb_imputed_haps_refined.R5.txt; adult_only_imputed_haps_refinedR5.txt